### ISSUE TITLE
Can not compile examples/agdk-egui?

### ISSUE THREAD

**Issue by sry948749099** [rib/android-activity#22]
I just clone this repository and `cd examples/agdk-egui`, run `cargo ndk -t arm64-v8a -o app/src/main/jniLibs/  build`, but meet errors:
![111](https://user-images.githubusercontent.com/56307410/187569471-19bd22b4-b78f-4685-80e1-a38979c1e8b5.png)
i had install the toolchains and cargo-ndk,

**Comment by rib** [comment]
Yeah, sorry I need to push an update to the examples since releasing `android-activity 0.2` and basing the updated Winit branch on that.

It could maybe also helpful to extend the `compile_error()` that's printed here to recommend checking `cargo tail` for multiple implementations of `android-activity` - which tends to be the most common cause for seeing this error (because only the implementation directly referenced by the app will have the required feature set)

Tbh I wish Cargo had a mechanism for enforcing that only a single version of a certain crate would be allowed - at least so that we could get a clearer error message for this kind of issue.

**Comment by rib** [comment]
oh and another issue I just realized is that this commit in Winit master: https://github.com/rib/winit/commit/da2cef97a3e63b8f73512b2c0c8d42020b7123e6 is a breaking change that affects (breaks) `egui_winit`.

I'll revert that patch on the winit backend branch for now (to avoid needing to create a temporary egui branch)

**Comment by rib** [comment]
hmm, actually I can't really just revert that on the winit branch since that branch is currently part of a pull request to try and upstream.
